version: '3.4'
services:
  fable:
    container_name: fable
    image: fable-image:latest
    restart: on-failure:10
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"

  db:                                                                                              
    image: 'postgres:13.2-alpine'                                                                  
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=logs
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # persist data even if container shuts down  
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql